services:
  app:
    image: ${DOCKERHUB_USERNAME}/express-app:latest
    ports:
      - "8383:8080"
    container_name: express-app
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
